# Generated by Django 5.2.11 on 2026-02-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('cilindrada', models.IntegerField()),
                ('potencia', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
        ),
    ]
