# Generated by Django 5.2.11 on 2026-02-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
