# Generated by Django 5.2.11 on 2026-02-11 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0002_alter_moto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('estrellas', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='resenas/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='motos.moto')),
            ],
        ),
    ]
