# Generated by Django 5.2.11 on 2026-02-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0003_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='motos/'),
        ),
    ]
